annotations:
  - border_color: '#00000000'
    border_style: ''
    color: '#F3F3F3'
    rotation: 0
    text_bold: false
    text_content: |-
      ------------------
      [IPSEC-R1]
      G1 | WAN | 12.100.0.2 | 12.100.0.0/30
      T0 | unnumbered |
      G2 | LAN | 172.16.20.1 | 172.16.20.0/29
      ------------------
      [IPSEC-INET]
      G1 | toLab01 | 12.100.0.1 | 12.100.0.0/30
      G2 | toLab02 | 20.50.7.2 | 20.5.7.0/30
      ------------------
      [IPSEC-R2]
      G1 | WAN | 20.5.7.1 | 20.5.7.0/30
      T0 | unnumbered |
      G2 | LAN | 10.50.3.1 | 10.50.3.0/29
      ------------------
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 160.0
    y1: -120.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#FFFFFF'
    rotation: 0
    text_bold: false
    text_content: |-
      ------------------
      [MGMT]
      IPSEC-WAN | 192.168.0.150
      IPSEC-R1  | 192.168.0.151
      IPSEC-R2  | 192.168.0.152
      ------------------
      IPSEC-HOST1 | 172.16.20.5/29
      ------------------
      IPSEC-HOST2 | 10.50.3.5/29
      ------------------
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -382.0
    y1: -38.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: .5   172.16.20.0/29   .1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -240.0
    y1: -160.0
    z_index: 2
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: .5   10.50.3.0/29   .1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -233.9140625
    y1: 337.0
    z_index: 3
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      .2

      12.100.0.0/30

      .1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -6.0
    y1: -60.0
    z_index: 4
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      .2

      20.5.7.0/30

      .1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -2.0
    y1: 154.0
    z_index: 5
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: iosxe_config.txt
        content: |-
          !CSR1000v
          hostname IPSEC-R1
          !
          vrf definition management
           !
           address-family ipv4
           exit-address-family
          !
          no logging console
          !
          no aaa new-model
          !
          ip domain name automation.lab
          !
          username sam privilege 15 password 0 cisco
          !
          ip ssh version 2
          crypto key generate rsa modulus 2048
          !
          no crypto ikev2 proposal default
          !
          no crypto ikev2 policy default
          !
          no crypto ipsec profile default
          !
          no crypto ipsec transform-set default
          !
          crypto isakmp policy 10
           encryption aes
           authentication pre-share
           group 14
           lifetime 3600
          !
          crypto isakmp key cisco123 address 20.5.7.1
          !
          crypto ipsec transform-set MYSET esp-aes esp-sha-hmac
           mode tunnel
          !
          crypto ipsec profile MYPROFILE
           set transform-set MYSET
          !
          interface Tunnel0
           ip unnumbered GigabitEthernet1
           tunnel source GigabitEthernet1
           tunnel mode ipsec ipv4
           tunnel destination 20.5.7.1
           tunnel protection ipsec profile MYPROFILE
          !
          interface GigabitEthernet1
           description to INET
           ip address 12.100.0.2 255.255.255.252
           negotiation auto
           no shut
          !
          interface GigabitEthernet2
           description to A1
           ip address 172.16.20.1 255.255.255.248
           negotiation auto
           no shut
          !
          interface GigabitEthernet4
           vrf forwarding management
           ip address 192.168.0.151 255.255.255.0
           negotiation auto
           no shut
          !
          !
          ip route 0.0.0.0 0.0.0.0 GigabitEthernet1
          ip route 10.50.3.0 255.255.255.248 Tunnel0
          ip route vrf management 0.0.0.0 0.0.0.0 192.168.0.1
          !
          !
          line con 0
           exec-timeout 0 0
           stopbits 1
          line vty 0 4
           exec-timeout 0 0
           login local
           length 0
           transport input ssh
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: IPSEC-R1
    node_definition: csr1000v
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: -120
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: iosxe_config.txt
        content: |-
          hostname IPSEC-ISP
          !
          vrf definition management
           !
           address-family ipv4
           exit-address-family
          !
          no logging console
          !
          no aaa new-model
          !
          ip domain name automation.lab
          !
          username netadmin privilege 15 password 0 samlab123
          !
          ip ssh version 2
          crypto key generate rsa modulus 2048
          !
          no crypto ikev2 proposal default
          !
          no crypto ikev2 policy default
          !
          no crypto ipsec profile default
          !
          no crypto ipsec transform-set default
          !
          !
          interface GigabitEthernet1
           description to lab01
           ip address 12.100.0.1 255.255.255.252
           no shut
          !
          interface GigabitEthernet2
           description to lab02
           ip address 20.5.7.2 255.255.255.252
           no shut
          !
          interface GigabitEthernet4
           vrf forwarding management
           ip address 192.168.0.150 255.255.255.0
           negotiation auto
           no shut
          !
          ip route vrf management 0.0.0.0 0.0.0.0 192.168.0.1
          !
          !
          line con 0
           exec-timeout 0 0
           stopbits 1
          line vty 0 4
           exec-timeout 0 0
           login local
           length 0
           transport input ssh
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: IPSEC-INET
    node_definition: csr1000v
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: 80
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: iosxe_config.txt
        content: |-
          !CSR1000v
          hostname IPSEC-R2
          !
          vrf definition management
           !
           address-family ipv4
           exit-address-family
          !
          no logging console
          !
          no aaa new-model
          !
          ip domain name automation.lab
          !
          username sam privilege 15 password 0 cisco
          !
          ip ssh version 2
          crypto key generate rsa modulus 2048
          !
          no crypto ikev2 proposal default
          !
          no crypto ikev2 policy default
          !
          no crypto ipsec profile default
          !
          no crypto ipsec transform-set default
          !
          crypto isakmp policy 10
           encryption aes
           authentication pre-share
           group 14
           lifetime 3600
          !
          crypto isakmp key cisco123 address 12.100.0.2
          !
          crypto ipsec transform-set MYSET esp-aes esp-sha-hmac
           mode tunnel
          !
          crypto ipsec profile MYPROFILE
           set transform-set MYSET
          !
          interface Tunnel0
           ip unnumbered GigabitEthernet1
           tunnel source GigabitEthernet1
           tunnel mode ipsec ipv4
           tunnel destination 12.100.0.2
           tunnel protection ipsec profile MYPROFILE
          !
          interface GigabitEthernet1
           description to INET
           ip address 20.5.7.1 255.255.255.252
           negotiation auto
           no shut
          !
          interface GigabitEthernet2
           description to A2
           ip address 10.50.3.1 255.255.255.248
           negotiation auto
           no shut
          !
          interface GigabitEthernet4
           vrf forwarding management
           ip address 192.168.0.152 255.255.255.0
           negotiation auto
           no shut
          !
          !
          ip route 0.0.0.0 0.0.0.0 GigabitEthernet1
          ip route 172.16.20.0 255.255.255.248 Tunnel0
          ip route vrf management 0.0.0.0 0.0.0.0 192.168.0.1
          !
          !
          line con 0
           exec-timeout 0 0
           stopbits 1
          line vty 0 4
           exec-timeout 0 0
           login local
           length 0
           transport input ssh
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: IPSEC-R2
    node_definition: csr1000v
    parameters: {}
    ram: null
    tags: []
    x: -40
    y: 280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |-
          # set hostname
          hostname IPSEC-HOST1

          # set credentials
          USERNAME=sam
          PASSWORD=cisco

          # configure networking
          ip addr add 172.16.20.5/29 dev eth0
          ip link set dev eth0 up
          ip route add 0.0.0.0/0 via 172.16.20.1
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: IPSEC-HOST1
    node_definition: alpine
    parameters: {}
    ram: null
    tags: []
    x: -240
    y: -120
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |-
          # set hostname
          hostname IPSEC-HOST2

          # set credentials
          USERNAME=sam
          PASSWORD=cisco

          # configure networking
          ip addr add 10.50.3.5/29 dev eth0
          ip link set dev eth0 up
          ip route add 0.0.0.0/0 via 10.50.3.1
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n4
    image_definition: null
    label: IPSEC-HOST2
    node_definition: alpine
    parameters: {}
    ram: null
    tags: []
    x: -240
    y: 280
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: hostname inserthostname-here
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: true
    id: n5
    image_definition: null
    label: MGMT-SW
    node_definition: ioll2-xe
    parameters: {}
    ram: null
    tags: []
    x: -480
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: Ethernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: default
        content: System Bridge
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n6
    image_definition: null
    label: MGMT-BRIDGE
    node_definition: external_connector
    parameters: {}
    ram: null
    tags: []
    x: -480
    y: 120
    interfaces:
      - id: i0
        label: port
        mac_address: null
        slot: 0
        type: physical
links:
  - id: l0
    n1: n0
    n2: n1
    i1: i1
    i2: i1
    conditioning: {}
    label: IPSEC-R1-GigabitEthernet1<->IPSEC-INET-GigabitEthernet1
  - id: l1
    n1: n1
    n2: n2
    i1: i2
    i2: i1
    conditioning: {}
    label: IPSEC-INET-GigabitEthernet2<->IPSEC-R2-GigabitEthernet1
  - id: l2
    n1: n3
    n2: n0
    i1: i0
    i2: i2
    conditioning: {}
    label: IPSEC-HOST1-eth0<->IPSEC-R1-GigabitEthernet2
  - id: l3
    n1: n4
    n2: n2
    i1: i0
    i2: i2
    conditioning: {}
    label: IPSEC-HOST2-eth0<->IPSEC-R2-GigabitEthernet2
  - id: l4
    n1: n6
    n2: n5
    i1: i0
    i2: i1
    conditioning: {}
    label: MGMT-BRIDGE-port<->MGMT-SW-Ethernet0/0
  - id: l5
    n1: n5
    n2: n0
    i1: i2
    i2: i4
    conditioning: {}
    label: MGMT-SW-Ethernet0/1<->IPSEC-R1-GigabitEthernet4
  - id: l6
    n1: n5
    n2: n1
    i1: i3
    i2: i4
    conditioning: {}
    label: MGMT-SW-Ethernet0/2<->IPSEC-INET-GigabitEthernet4
  - id: l7
    n1: n5
    n2: n2
    i1: i4
    i2: i4
    conditioning: {}
    label: MGMT-SW-Ethernet0/3<->IPSEC-R2-GigabitEthernet4
lab:
  description: ''
  notes: ''
  title: VPNs-BaseConfigPlusWorkingVTI
  version: 0.3.0
